# Generated by Django 4.2.7 on 2025-11-18 21:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'db_table': 'pricing_rules',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Condo', 'Condo'), ('Villa', 'Villa'), ('Townhouse', 'Townhouse'), ('Loft', 'Loft'), ('Studio', 'Studio'), ('Penthouse', 'Penthouse'), ('Cottage', 'Cottage'), ('Bungalow', 'Bungalow')], db_index=True, max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, geography=True, srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bedrooms', models.IntegerField(db_index=True)),
                ('bathrooms', models.DecimalField(db_index=True, decimal_places=1, max_digits=3)),
                ('max_guests', models.IntegerField()),
                ('base_price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(db_index=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rentals.property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'verbose_name_plural': 'Property Amenities',
                'db_table': 'property_amenities',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type'], name='properties_city_a8f31b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['base_price_per_night'], name='properties_base_pr_dd0269_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'bathrooms'], name='properties_bedroom_2aae3d_idx'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='rentals.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.property'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['property', 'start_date', 'end_date'], name='pricing_rul_propert_f1f1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'check_in', 'check_out'], name='bookings_propert_bccde0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
    ]
